### ISSUE TITLE
Other language

### ISSUE THREAD

**Issue by Irwine** [tr4wzified/DisplaySpellTomeLevelPatcher#5]
I'm french translator and using that's patcher, not working in my language.
I suppose it's due to a different name for spell tome and scrolls

In my language :
Spell tome : => Livre de sort -
Scroll of => Parchemin -

The results of names with level are :
For spell tome
(level}) Livre de sort - 
For scrolls
({level}) Parchemin - 

The differents level need a translation too, they are :

"Novice",
"Apprenti",
"Adepte",
"Expert",
"Maître" or "Maître, if î made issues.

**Comment by tr4wzified** [comment]
I'm fine with supporting this via a settings option, but I don't really feel like implementing language support myself. It's more work than I thought since I unfortunately can't seem to load up xEdit in French, even with the -l:fr argument and setting my game to French.

If there are any coders interested in extending the patcher to support French or any other language, I'm open to pull requests fixing that up but I feel like it's too much of a niche to be spending my own time on.

**Comment by Irwine** [comment]
Hi,

I can do that's the easier option is to translate the required parameters
and upload the translated version.

I dont have access to my computer now, but I'll made and test this french
version as i can.

The only question that's i had is do you prefer that's i upload this
version on my github or send it to you ?

Le mar. 27 avr. 2021 à 13:38, trawzified ***@***.***> a
écrit :

**Comment by tr4wzified** [comment]
Sure, that's alright too. Open a PR for it on GitHub. You can fork this repository, make the changes on yours and open a PR, I can adjust things from there.

**Comment by Irwine** [comment]
Ok, I'll do that.

Le mar. 27 avr. 2021 à 16:53, trawzified ***@***.***> a
écrit :
